name: Build and deploy in Firebase Hosting (Development)
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Install node dependencies
        run: yarn install
      - name: Build (Development) artifact
        env:
          CI: false
        run: >
          yarn run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:${{ secrets.FIREBASE_TARGET_DEV }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}